import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Header from '@/components/organisms/Header';
import Footer from '@/components/organisms/Footer';

import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Hyperhire Assessment',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
